[connections.supabase]
SUPABASE_URL = "https://hbaqxtmpqcgkmvbpwkkh.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiYXF4dG1wcWNna212YnB3a2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEzNzAxNDgsImV4cCI6MjA0Njk0NjE0OH0.FAQdLAeKkdNWXZs23U96KUZ0dnI4kfjfSw3sUPriO9Q"